import nodemailer from 'nodemailer';

// Create reusable transporter object using SMTP transport
const createTransporter = () => {
  // Check if email service is configured
  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
    console.log('⚠️  Email service not configured - emails will be logged instead of sent');
    return null;
  }

  const port = parseInt(process.env.EMAIL_PORT) || 587;
  const secure = process.env.EMAIL_SECURE === 'true' || port === 465;
  
  console.log('📧 Email transporter configuration:', {
    service: process.env.EMAIL_SERVICE || 'gmail',
    host: process.env.EMAIL_HOST || 'smtp.gmail.com',
    port: port,
    secure: secure,
    user: process.env.EMAIL_USER ? '✅ Set' : '❌ Not set',
    pass: process.env.EMAIL_PASS ? '✅ Set' : '❌ Not set'
  });
  
  return nodemailer.createTransport({
    service: process.env.EMAIL_SERVICE || 'gmail',
    host: process.env.EMAIL_HOST || 'smtp.gmail.com',
    port: port,
    secure: secure,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS
    },
    // Add timeout and connection options
    connectionTimeout: parseInt(process.env.EMAIL_CONNECTION_TIMEOUT) || 10000,
    greetingTimeout: parseInt(process.env.EMAIL_GREETING_TIMEOUT) || 5000,
    socketTimeout: parseInt(process.env.EMAIL_SOCKET_TIMEOUT) || 10000,
    // Force IPv4 to avoid IPv6 connectivity issues
    family: 4,
    // Retry options
    pool: true,
    maxConnections: 5,
    maxMessages: 100,
    // TLS options
    tls: {
      rejectUnauthorized: false,
      ciphers: 'SSLv3'
    },
    // Additional debugging - disabled to reduce console noise
    // debug: process.env.NODE_ENV === 'development',
    // logger: process.env.NODE_ENV === 'development'
  });
};

// Mock email sending for development/testing
const mockEmailSend = async (mailOptions) => {
  console.log('📧 MOCK EMAIL SEND (Email service not configured):');
  console.log('From:', mailOptions.from);
  console.log('To:', mailOptions.to);
  console.log('Subject:', mailOptions.subject);
  console.log('HTML Length:', mailOptions.html ? mailOptions.html.length : 0, 'characters');
  console.log('Text Length:', mailOptions.text ? mailOptions.text.length : 0, 'characters');
  console.log('---');
  
  return {
    messageId: 'mock-' + Date.now(),
    response: 'Mock email sent successfully'
  };
};

// Send contact form notification to admin
export const sendContactNotification = async (contactData) => {
  try {
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      console.log('Email service not configured. Skipping email notification.');
      return;
    }

    const transporter = createTransporter();

    const mailOptions = {
      from: `"Bahoju Tech Website" <${process.env.EMAIL_USER}>`,
      to: process.env.EMAIL_USER, // Send admin notifications to your Gmail
      subject: `New Contact Form Submission - ${contactData.inquiryType}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #0573A0; border-bottom: 2px solid #0573A0; padding-bottom: 10px;">
            New Contact Form Submission
          </h2>
          
          <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #333; margin-top: 0;">Contact Information</h3>
            <p><strong>Name:</strong> ${contactData.firstName} ${contactData.lastName}</p>
            <p><strong>Email:</strong> ${contactData.email}</p>
            <p><strong>Company:</strong> ${contactData.company}</p>
            <p><strong>Inquiry Type:</strong> ${contactData.inquiryType}</p>
            <p><strong>Submitted:</strong> ${new Date(contactData.createdAt).toLocaleString()}</p>
          </div>
          
          <div style="background-color: #fff; padding: 20px; border: 1px solid #dee2e6; border-radius: 8px;">
            <h3 style="color: #333; margin-top: 0;">Message</h3>
            <p style="line-height: 1.6; color: #555;">${contactData.message}</p>
          </div>
          
          <div style="margin-top: 30px; padding: 15px; background-color: #e7f3ff; border-radius: 8px;">
            <p style="margin: 0; color: #0573A0; font-size: 14px;">
              <strong>Action Required:</strong> Please respond to this inquiry within 24 hours.
            </p>
          </div>
          
          <hr style="margin: 30px 0; border: none; border-top: 1px solid #dee2e6;">
          <p style="color: #6c757d; font-size: 12px; text-align: center;">
            This email was automatically generated by the Bahoju Tech website contact form.
          </p>
        </div>
      `
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('Contact notification email sent:', info.messageId);
    return info;
  } catch (error) {
    console.error('Error sending contact notification email:', error);
    throw error;
  }
};

// Send welcome email to new users
export const sendWelcomeEmail = async (userData) => {
  try {
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      console.log('Email service not configured. Skipping welcome email.');
      return;
    }

    const transporter = createTransporter();

    const mailOptions = {
      from: `"Bahoju Tech" <${process.env.EMAIL_USER}>`,
      to: userData.email,
      subject: 'Welcome to Bahoju Tech!',
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background-color: #0573A0; color: white; padding: 30px; text-align: center; border-radius: 8px 8px 0 0;">
            <h1 style="margin: 0; font-size: 28px;">Welcome to Bahoju Tech!</h1>
          </div>
          
          <div style="padding: 30px; background-color: #f8f9fa;">
            <h2 style="color: #333;">Hello ${userData.name}!</h2>
            <p style="line-height: 1.6; color: #555;">
              Thank you for joining Bahoju Tech. We're excited to have you as part of our community!
            </p>
            
            <div style="background-color: white; padding: 20px; border-radius: 8px; margin: 20px 0;">
              <h3 style="color: #0573A0; margin-top: 0;">What's Next?</h3>
              <ul style="color: #555; line-height: 1.8;">
                <li>Explore our latest blog posts and insights</li>
                <li>Stay updated with our latest tech solutions</li>
                <li>Connect with our team for any inquiries</li>
              </ul>
            </div>
            
            <div style="text-align: center; margin: 30px 0;">
              <a href="${process.env.FRONTEND_URL}" 
                 style="background-color: #0573A0; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block;">
                Visit Our Website
              </a>
            </div>
          </div>
          
          <div style="background-color: #333; color: white; padding: 20px; text-align: center; border-radius: 0 0 8px 8px;">
            <p style="margin: 0; font-size: 14px;">
              Bahoju Tech - Innovate. Elevate. Dominate.
            </p>
          </div>
        </div>
      `
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('Welcome email sent:', info.messageId);
    return info;
  } catch (error) {
    console.error('Error sending welcome email:', error);
    throw error;
  }
};

// Send password reset email
export const sendPasswordResetEmail = async (userData, resetToken) => {
  try {
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      console.log('Email service not configured. Skipping password reset email.');
      return;
    }

    const transporter = createTransporter();
    const resetUrl = `${process.env.FRONTEND_URL}/reset-password?token=${resetToken}`;

    const mailOptions = {
      from: `"Bahoju Tech" <${process.env.EMAIL_USER}>`,
      to: userData.email,
      subject: 'Password Reset Request - Bahoju Tech',
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #0573A0; border-bottom: 2px solid #0573A0; padding-bottom: 10px;">
            Password Reset Request
          </h2>
          
          <div style="padding: 20px; background-color: #f8f9fa; border-radius: 8px; margin: 20px 0;">
            <p style="color: #333; line-height: 1.6;">Hello ${userData.name},</p>
            <p style="color: #555; line-height: 1.6;">
              We received a request to reset your password for your Bahoju Tech account. 
              If you made this request, please click the button below to reset your password:
            </p>
            
            <div style="text-align: center; margin: 30px 0;">
              <a href="${resetUrl}" 
                 style="background-color: #0573A0; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block;">
                Reset Password
              </a>
            </div>
            
            <p style="color: #666; font-size: 14px; line-height: 1.6;">
              This link will expire in 1 hour for security reasons. If you didn't request this password reset, 
              please ignore this email and your password will remain unchanged.
            </p>
          </div>
          
          <hr style="margin: 30px 0; border: none; border-top: 1px solid #dee2e6;">
          <p style="color: #6c757d; font-size: 12px; text-align: center;">
            If you're having trouble clicking the button, copy and paste this URL into your browser:<br>
            <span style="word-break: break-all;">${resetUrl}</span>
          </p>
        </div>
      `
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('Password reset email sent:', info.messageId);
    return info;
  } catch (error) {
    console.error('Error sending password reset email:', error);
    throw error;
  }
};

// Send auto-response email to user based on inquiry type
export const sendAutoResponseEmail = async (contactData) => {
  try {
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      console.log('Email service not configured. Skipping auto-response email.');
      return;
    }

    const transporter = createTransporter();
    
    // Get response content based on inquiry type
    const getResponseContent = (inquiryType) => {
      switch (inquiryType) {
        case 'TECH SERVICES':
          return {
            subject: 'Thank you for your Tech Services Inquiry - Bahoju Tech',
            content: `
              <h2>Technology Services Inquiry Received</h2>
              <p>Thank you for your interest in our technology services! We're excited to help transform your business with cutting-edge solutions.</p>
              
              <div style="background-color: #e7f3ff; padding: 20px; border-radius: 8px; margin: 20px 0;">
                <h3 style="color: #0573A0; margin-top: 0;">Our Tech Services Include:</h3>
                <ul style="color: #555; line-height: 1.8;">
                  <li>Custom Software Development</li>
                  <li>Cloud Infrastructure Solutions</li>
                  <li>Mobile App Development</li>
                  <li>Web Development & Design</li>
                  <li>Digital Transformation Consulting</li>
                  <li>System Integration & API Development</li>
                  <li>Quality Assurance</li>
                  <li>Project Management</li>
                  <li>IT Support & Maintenance</li>
                  <li>Security Solutions</li>
                  <li>Blog Development & Management</li>
                </ul>
              </div>
              
              <p style="color: #555; line-height: 1.6;">
                Our technical team will review your requirements and get back to you within 24 hours with a detailed proposal tailored to your needs.
              </p>
            `
          };
        
        case 'TRAINING':
          return {
            subject: 'Thank you for your Training Inquiry - Bahoju Tech',
            content: `
              <h2>Training Program Inquiry Received</h2>
              <p>Thank you for your interest in our professional training programs! We're committed to empowering individuals and teams with the latest tech skills.</p>
              
              <div style="background-color: #e7f3ff; padding: 20px; border-radius: 8px; margin: 20px 0;">
                <h3 style="color: #0573A0; margin-top: 0;">Our Training Programs:</h3>
                <ul style="color: #555; line-height: 1.8;">
                  <li>Full-Stack Web Development</li>
                  <li>Backend Development</li>
                  <li>Frontend Development</li>
                  <li>Cybersecurity</li>
                  <li>Mobile App Development (React Native, Flutter)</li>
                  <li>Cloud Computing (AWS, Azure, Google Cloud)</li>
                  <li>Digital Marketing & SEO</li>
                  <li>UI/UX Design</li>
                  <li>Data Science & Analytics</li>
                  <li>Cybersecurity + ETHICAL HACKING</li>
                  <li>Project Management</li>
                  <li>Data Analysis</li>
                  <li>Digital Marketing & SEO</li>
                  <li>Visual and Graphic Design</li>
                </ul>
              </div>
              
              <p style="color: #555; line-height: 1.6;">
                Our training coordinator will contact you within 24 hours to discuss program details, schedules, and enrollment options.
              </p>
            `
          };
        
        case 'INTERNSHIP':
          return {
            subject: 'Thank you for your Internship Inquiry - Bahoju Tech',
            content: `
              <h2>Internship Opportunity Inquiry Received</h2>
              <p>Thank you for your interest in joining our internship program! We're always looking for passionate individuals to join our dynamic team.</p>
              
              <div style="background-color: #e7f3ff; padding: 20px; border-radius: 8px; margin: 20px 0;">
                <h3 style="color: #0573A0; margin-top: 0;">Internship Opportunities:</h3>
                <ul style="color: #555; line-height: 1.8;">
                  <li>Software Development Internship</li>
                  <li>Backend Development Internship</li>
                  <li>Frontend Development Internship</li>
                  <li>Cybersecurity Internship</li>
                  <li>UI/UX Design Internship</li>
                  <li>Digital Marketing Internship</li>
                  <li>Data Analysis Internship</li>
                  <li>Project Management Internship</li>
                  <li>Quality Assurance Internship</li>
                </ul>
              </div>
              
              <p style="color: #555; line-height: 1.6;">
                Our HR team will review your inquiry and contact you within 48 hours to discuss available positions and next steps in the application process.
              </p>
            `
          };
        
        default:
          return {
            subject: 'Thank you for contacting Bahoju Tech',
            content: `
              <h2>Your Inquiry Has Been Received</h2>
              <p>Thank you for reaching out to Bahoju Tech! We appreciate your interest in our services.</p>
              
              <p style="color: #555; line-height: 1.6;">
                Our team will review your message and get back to you within 24 hours with a detailed response.
              </p>
            `
          };
      }
    };

    const responseContent = getResponseContent(contactData.inquiryType);
    const companyInfo = contactData.company ? `<p><strong>Company:</strong> ${contactData.company}</p>` : '';

    const mailOptions = {
      from: `"Bahoju Tech" <${process.env.EMAIL_USER}>`,
      to: contactData.email,
      subject: responseContent.subject,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background-color: #0573A0; color: white; padding: 30px; text-align: center; border-radius: 8px 8px 0 0;">
            <h1 style="margin: 0; font-size: 24px;">Bahoju Tech</h1>
            <p style="margin: 10px 0 0 0; opacity: 0.9;">Innovate. Elevate. Dominate.</p>
          </div>
          
          <div style="padding: 30px; background-color: #f8f9fa;">
            <h2 style="color: #333;">Hello ${contactData.firstName}!</h2>
            
            ${responseContent.content}
            
            <div style="background-color: white; padding: 20px; border-radius: 8px; margin: 30px 0; border-left: 4px solid #0573A0;">
              <h3 style="color: #333; margin-top: 0;">Your Inquiry Details:</h3>
              <p><strong>Name:</strong> ${contactData.firstName} ${contactData.lastName}</p>
              <p><strong>Email:</strong> ${contactData.email}</p>
              ${companyInfo}
              <p><strong>Inquiry Type:</strong> ${contactData.inquiryType}</p>
              <p><strong>Submitted:</strong> ${new Date(contactData.createdAt).toLocaleString()}</p>
            </div>
            
            <div style="text-align: center; margin: 30px 0;">
              <a href="${process.env.FRONTEND_URL}" 
                 style="background-color: #0573A0; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block;">
                Visit Our Website
              </a>
            </div>
            
            <div style="background-color: #fff3cd; padding: 15px; border-radius: 8px; border-left: 4px solid #ffc107;">
              <p style="margin: 0; color: #856404; font-size: 14px;">
                <strong>Need immediate assistance?</strong> Feel free to call us at +234 8073762546 or email us directly at ${process.env.EMAIL_USER}
              </p>
            </div>
          </div>
          
          <div style="background-color: #333; color: white; padding: 20px; text-align: center; border-radius: 0 0 8px 8px;">
            <p style="margin: 0; font-size: 14px;">
              © 2024 Bahoju Tech. All rights reserved.
            </p>
            <p style="margin: 5px 0 0 0; font-size: 12px; opacity: 0.8;">
              This is an automated response. Please do not reply to this email.
            </p>
          </div>
        </div>
      `
    };

    console.log('📧 Sending auto-response email to:', contactData.email);
    const info = await transporter.sendMail(mailOptions);
    console.log('✅ Auto-response email sent successfully!');
    console.log('Message ID:', info.messageId);
    return info;
  } catch (error) {
    console.error('❌ Error sending auto-response email:', error.message);
    console.error('Full error:', error);
    throw error;
  }
};

// Generic send email function
export const sendEmail = async ({ to, subject, html, text }) => {
  try {
    const transporter = createTransporter();

    const mailOptions = {
      from: `"Bahoju Tech" <${process.env.EMAIL_USER || 'noreply@bahoju.com'}>`,
      to,
      subject,
      html,
      text
    };

    // Use mock email if transporter is null (no email config)
    if (!transporter) {
      return await mockEmailSend(mailOptions);
    }

    // Try to send real email with timeout handling
    const info = await Promise.race([
      transporter.sendMail(mailOptions),
      new Promise((_, reject) => 
        setTimeout(() => reject(new Error('Email send timeout after 15 seconds')), 15000)
      )
    ]);

    console.log('✅ Email sent successfully:', info.messageId);
    return info;
  } catch (error) {
    console.error('❌ Error sending email:', error.message);
    
    // If it's a connection timeout or auth error, fall back to mock
    if (error.code === 'ETIMEDOUT' || error.code === 'EAUTH' || error.message.includes('timeout')) {
      console.log('📧 Falling back to mock email due to connection issues...');
      const mailOptions = {
        from: `"Bahoju Tech" <${process.env.EMAIL_USER || 'noreply@bahoju.com'}>`,
        to,
        subject,
        html,
        text
      };
      return await mockEmailSend(mailOptions);
    }
    
    throw error;
  }
};

// Test email configuration
export const testEmailConfiguration = async () => {
  try {
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      throw new Error('Email configuration is missing');
    }

    const transporter = createTransporter();
    await transporter.verify();
    console.log('✅ Email service is configured and ready');
    return true;
  } catch (error) {
    console.error('❌ Email service configuration error:', error.message);
    return false;
  }
};
